### PR TITLE
Created two subnets in us-east-1 and us-west-2 (10.132.60.0/22)

### PR DESCRIPTION
**Pull request by ciobancai**

### CODE REVIEW

**Comment by kmoir** [comment]
You also need to update configs/tst-linux64 and configs/tst-emulator64 to include the new subnets as appropriate

see 
https://bugzilla.mozilla.org/show_bug.cgi?id=1165432#c1

**Comment by ciobancai** [comment]
From what I understood the script creates the subnets and after that I will need to add them in the configs/tst-linux64 and configs/tst-emulator64

**Comment by kmoir** [comment]
Note from callek re fixing the upstream issue that caused the tests to fail
Callek> kmoir: https://github.com/seandst/cfn-pyplates/pull/43

I reran tox in my docker image after this was fixed and the tests passed

**Comment by ciobancai** [comment]
Wrong pull request

**Pull request closed without merging**
