### PR TITLE
Bug 1195880: disable windows update at boot, if enabled

### PR DESCRIPTION
**Pull request by grenade**
This PR updates 2008 userdata powershell to disable windows updates if the instance has them enabled. Additionally, Ec2UserdataUtils.psm1 was not source controlled (just hosted at http://releng-puppet2.srv.releng.scl3.mozilla.com/repos/powershell/Ec2UserdataUtils.psm1). I have included it here so that we can track changes.

### CODE REVIEW

**Comment by djmitche** [comment]
How does automation find that `.psm1` file?

**Comment by grenade** [comment]
It's currently hardcoded into userdata (https://github.com/mozilla/build-cloud-tools/blob/master/configs/b-2008.user-data#L95). I have [another bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1195877) to clean that up when I fix passing of the puppet_server token to userdata.

**Comment by djmitche** [comment]
The fixup sounds good to avoid the link to a single (possibly down) master.  I'd like to see that file somehow synchronized with the version you're adding to git, though.

**Comment by grenade** [comment]
Yes, been thinking the same. I've noted it in the puppet_server token bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1195877#c1 and will either fix then, or create a new bug.

**Pull request merged**
