### PR TITLE
Bug 1116271: Manage the Releng Network in us-west-2

### PR DESCRIPTION
**Pull request by djmitche**
This defines the releng network and is currently deployed as it appears in this patch.

There's an AWS bug around customer gateways that means this stack will "steal" the existing CGW if the IP and ASN match.  So I've faked them out for the moment.  Wen we're ready to deploy, I'll reset those to their proper values, delete the existing customer gateway, and update this stack (or re-create if there's some other bug).  Once that's done, I'll move nagios1 to the appropriate new subnet, and the delete all the old cruft.  And we'll be deploy'd!

### CODE REVIEW

**Comment by djmitche** [comment]
Hm, small issue with the tests..

**Comment by djmitche** [comment]
that should fix it

**Comment by rail** [comment]
Looks great to me! Feel free to merge it whenever you are ready.

**Comment by djmitche** [comment]
I'll merge tomorrow.

**Pull request merged**
