### PR TITLE
Bug 1126428: remove individual masters from security groups

### PR DESCRIPTION
**Pull request by djmitche**
I've deplyed this already, but here it is.  Note that dev-master1 is still in srv, but it's listed elsewhere (below this hunk).

### CODE REVIEW

**Comment by djmitche** [comment]
Added a missed flow, identified by firewall-tests.

**Comment by djmitche** [comment]
(also now deployed)

**Comment by rail** [comment]
@djmitche do you want to mere this?

**Comment by djmitche** [comment]
Yes, I was waiting for a :+1: but I'll take that :)

**Pull request merged**
