### PR TITLE
Negative Lookahead for b2g_emulator_vm_large to make sure we spin emulat...

### PR DESCRIPTION
**Pull request by Callek**
...or and not less-powerful instances

Solves
FAIL-MULTI-MATCH     tst-emulator64   tst-linux64,tst-emulator64 b2g_emulator_vm_large cedar opt test mochitest-media

### CODE REVIEW

**Comment by djmitche** [comment]
I looked at this but I don't really understand the intent.

**Comment by Callek** [comment]
When _large is matched we should be launching an emulator instance, (which is matched below), the fact that we have "multi match" here means that we are indeterminent on which launches, the negative lookahead here prevents us matching the wrong one for _large.

**Comment by djmitche** [comment]
ok, :+1:

**Pull request merged**
