### PR TITLE
Bug 1188928: Renamed try-2008 to y-2008

### PR DESCRIPTION
**Pull request by grenade**
Due to a character limit for EC2 Windows hostnames, we are shortening the naming convention for try Windows 2008 hosts from try-2008-ec2-* and try-2008-spot-* to y-2008-ec2-* and y-2008-spot-*. This PR replaces references to 'try-2008' with 'y-2008'

### CODE REVIEW

**Comment by Callek** [comment]
if possible can we hold off on merging this, we have a naming doc that we have used for a pretty good reason, and I would hate to diverge from established norms too far for this.

Basically don't use "try-" or "y-" for the name, use "b-" per https://wiki.mozilla.org/ReleaseEngineering/Slave_Naming

**Comment by amyrrich** [comment]
On 3 Aug 2015, at 11:58, Justin Wood (Callek) wrote:

> if possible can we hold off on merging this, we have a naming doc that 
> we have used for a pretty good reason, and I would hate to diverge 
> from established norms too far for this.
>
> Basically don't use "try-" or "y-" for the name, use "b-" per 
> https://wiki.mozilla.org/ReleaseEngineering/Slave_Naming

We had a conversation about this with rail/catlee/etc and were asked NOT 
to have the same name for build and try in AWS. We need to update the 
naming doc to reflect that, though.

**Comment by Callek** [comment]
@ccooper expressed distaste to me about arbitrary changing of naming schemes vs what was in that naming doc, so I'd love this (divergence from establish norms, ala use of 'y') to wait at least until coop and/or catlee can signoff on it, unless this is a hard blocker to other work.

I also note that the maintained-by-coop slave health page has "b-2008" for try windows as well: https://secure.pub.build.mozilla.org/builddata/reports/slave_health/index.html

**Comment by amyrrich** [comment]
We discussed this a couple months ago and catlee had already agreed to the new naming scheme if we couldn't use try- because of the 15 char length. Coop was also on board as long as we updated the documentation with the reasoning.

https://wiki.mozilla.org/ReleaseEngineering/Slave_Naming updated to reflect the y- naming scheme and remove a bunch of outdated information.

**Pull request merged**
