### PR TITLE
Bug 1122769: make cloud-tools a real Python package/dist

### PR DESCRIPTION
**Pull request by djmitche**
Lots of renames here.  Note that the top-level `scripts` remains as a symlink, so existing stuff that runs scripts using `python scripts/aws_foo.py` should still work

For each script:
 * add an entry point
 * make the `if __name__ == "__main__"` line just invoke `main()`, which is what the entry point points at
  * remove some unused local variables that appear to flake8 now that `main` is a function
 * remove the now-superfluous `site.addsitedir` call
 * adjust imports
 * pep8

### CODE REVIEW

**Comment by rail** [comment]
Oooh! Thanks a lot for this improvement.
In overall it looks good to me. The only concern now is how to properly deploy it on aws-manager1. Let's figure it out next week.

**Comment by djmitche** [comment]
I don't think it would make a difference - the scripts are still available at the same path, and still work.  But I haven't tested that.  And, it would be nice to install the package on aws-manager1 and have the entry points in $PATH, anyway.

**Comment by rail** [comment]
Ah... I didn't notice the scripts symlink. Let's merge it tomorrow then!

**Comment by rail** [comment]
I had to revert the change because the scripts were unable to find the modules. Probably this needs a bit puppet love.

**Pull request merged**
