### PR TITLE
the start of a readme...

### PR DESCRIPTION
**Pull request by grenade**
...including the steps I took to install on Fedora 22

### CODE REVIEW

**Comment by djmitche** [comment]
+1 to adding a README, but -1 to suggesting pip installing globally on your system!

I don't know if we have any general releng documentation on developing with virtualenv -- Buildbot has http://trac.buildbot.net/wiki/RunningBuildbotWithVirtualEnv

You'll still need Python and MySQL-devel, but add Virtualenv to the mix.  Then set up a virtualenv named `sandbox`:

```
virtualenv sandbox
```

and install cloud-tools into it:

```
sandbox/bin/pip install -e .
```

That way the install of cloud-tools and all of its dependencies is isolated to that virtualenv.

**Comment by grenade** [comment]
Cleaning up from a global install looks like this:

    sudo pip uninstall builds/aws_manager/cloud-tools
    sudo pip uninstall boto
    sudo easy_install -m pip
    sudo pip uninstall pip # `easy_install -m` leaves a little behind...

**Comment by djmitche** [comment]
This looks much better.  I'm curious why you need to pip install boto separately, though -- it's included in [the requirements](https://github.com/mozilla/build-cloud-tools/blob/master/setup.py#L20).

Anyway, good to merge.

**Comment by grenade** [comment]
I don't think there was any reason for it to be there. Just an artefact of my infamiliarity with the tools.

**Pull request merged**
