### PR TITLE
Bug 1126428: add a new CentOS-6.5 server image

### PR DESCRIPTION
**Pull request by djmitche**
I'm running this now.  I set size to 15, since that's the size of the root disk on bm76 right now.  The rest is a copy from centos-65-x86_64-hvm-base.

### CODE REVIEW

**Comment by djmitche** [comment]
```
INFO:cloudtools.scripts.aws_create_ami:Creating a snapshot
INFO:cloudtools.scripts.aws_create_ami:Creating AMI
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-virtualization-type: hvm
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-type: server-linux64
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-instance-family: c3
INFO:cloudtools.scripts.aws_create_ami:AMI created
INFO:cloudtools.scripts.aws_create_ami:ID: ami-ef471cdf, name: centos-65-x86_64-hvm-server-2015-02-03-19-35
INFO:cloudtools.scripts.aws_create_ami:Deleting volume
INFO:cloudtools.scripts.aws_create_ami:Terminating host instance
INFO:cloudtools.scripts.aws_create_ami:Copying ami-ef471cdf (centos-65-x86_64-hvm-server-2015-02-03-19-35) to us-east-1
INFO:cloudtools.aws.ami:Copying Image:ami-ef471cdf to us-east-1
INFO:cloudtools.aws.ami:AMI created
INFO:cloudtools.aws.ami:ID: ami-ca783ba2, name: None
INFO:cloudtools.scripts.aws_create_ami:New AMI created. AMI ID: ami-ca783ba2
INFO:cloudtools.scripts.aws_create_ami:Copying ami-ef471cdf (centos-65-x86_64-hvm-server-2015-02-03-19-35) to us-west-1
INFO:cloudtools.aws.ami:Copying Image:ami-ef471cdf to us-west-1
INFO:cloudtools.aws.ami:AMI created
INFO:cloudtools.aws.ami:ID: ami-c0bca485, name: None
INFO:cloudtools.scripts.aws_create_ami:New AMI created. AMI ID: ami-c0bca485
```
It's not clear from irc conversations whether I should build buildmaster instances with these AMIs or directly from the hvm-base images.  The only difference is the size, and I don't recall if that's important in this case.

**Comment by djmitche** [comment]
```
16:19 < rail> dustin: the AMI looks good, I managed to launch an instances (c3.large)
16:21 < rail> dustin: I think the offender is https://github.com/mozilla/build-cloud-tools/blob/master/configs/buildbot-master#L14
16:21 < rail> sda1 vs sda
```

**Comment by djmitche** [comment]
On rail's further advice I copied the device map from bld-linux64 and that seems to have worked.

There's an issue with the puppetization process, though:
```
Wed Feb 04 15:53:52 -0800 2015 Puppet (err): Execution of '/bin/rpm -e ssmtp-2.61-15.el6.x86_64' returned 1: error: Failed dependencies:
        /usr/bin/mailq is needed by (installed) nagios-plugins-mailq-1.4.15-2.el6.x86_64
        /usr/sbin/sendmail is needed by (installed) cronie-1.4.4-12.el6.x86_64
Wed Feb 04 15:53:52 -0800 2015 /Stage[main]/Packages::Postfix/Package[ssmtp]/ensure (err): change from 2.61-15.el6 to absent failed: Execution of '/bin/rpm -e ssmtp-2.61-15.el6.x86_64' returned 1: error: Failed dependencies:
        /usr/bin/mailq is needed by (installed) nagios-plugins-mailq-1.4.15-2.el6.x86_64
        /usr/sbin/sendmail is needed by (installed) cronie-1.4.4-12.el6.x86_64
```
I don't see any record of ssmtp being installed, ever, on an onsite host (bm103).  So I wonder if it's being installed as part of the base image by `aws_create_ami`.  Timestamps in `/var/log/yum.log` on rpmpackager1 suggest that's the case.

cronie and nagios-plugins-mailq require a virtual package that's being satisfied with ssmtp, but could also be satisfied with postfix.  However, making the switch requires switching within a single yum transaction, and puppet (still) doesn't support yum transactions.

**Comment by djmitche** [comment]
Ah, yes, it's because the base images install "Base" and not just "Core".

**Comment by rail** [comment]
I think, this is why we have https://github.com/mozilla/build-cloud-tools/blob/master/ami_configs/centos-62-x86_64-server/additional_packages#L4

**Comment by djmitche** [comment]
Right, but using a different initial set of packages results in different behaviors between onsite and off-site hosts.  Adding a third way of installing packages doesn't fix that :)

**Comment by djmitche** [comment]
With just Core, I built
```
INFO:cloudtools.scripts.aws_create_ami:Creating a snapshot
INFO:cloudtools.scripts.aws_create_ami:Creating AMI
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-virtualization-type: hvm
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-type: server-linux64
INFO:cloudtools.scripts.aws_create_ami:Tagging moz-instance-family: c3
INFO:cloudtools.scripts.aws_create_ami:AMI created
INFO:cloudtools.scripts.aws_create_ami:ID: ami-4da2f97d, name: centos-65-x86_64-hvm-server-2015-02-05-01-36
INFO:cloudtools.scripts.aws_create_ami:Deleting volume
INFO:cloudtools.scripts.aws_create_ami:Terminating host instance
INFO:cloudtools.scripts.aws_create_ami:Copying ami-4da2f97d (centos-65-x86_64-hvm-server-2015-02-05-01-36) to us-east-1
INFO:cloudtools.aws.ami:Copying Image:ami-4da2f97d to us-east-1
INFO:cloudtools.aws.ami:AMI created
INFO:cloudtools.aws.ami:ID: ami-30d39158, name: None
INFO:cloudtools.scripts.aws_create_ami:New AMI created. AMI ID: ami-30d39158
INFO:cloudtools.scripts.aws_create_ami:Copying ami-4da2f97d (centos-65-x86_64-hvm-server-2015-02-05-01-36) to us-west-1
INFO:cloudtools.aws.ami:Copying Image:ami-4da2f97d to us-west-1
INFO:cloudtools.aws.ami:AMI created
INFO:cloudtools.aws.ami:ID: ami-72405b37, name: None
INFO:cloudtools.scripts.aws_create_ami:New AMI created. AMI ID: ami-72405b37
```

**Comment by djmitche** [comment]
And that's failing with
```
xlblk_init: register_blkdev major: 202 

%Gblkfront: xvda: barriers disabled

 xvda: xvda1 xvda2

blkfront: xvdb: barriers disabled

 xvdb: unknown partition table

blkfront: xvdc: barriers disabled

 xvdc: unknown partition table

Refined TSC clocksource calibration: 2793.267 MHz.

Switching to clocksource tsc

input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4

dracut Warning: No root device "block:/dev/disk/by-label/root_dev" found







%G







dracut Warning: Boot has failed. To debug this issue add "rdshell" to the kernel command line.





dracut Warning: Signal caught!



dracut Warning: Boot has failed. To debug this issue add "rdshell" to the kernel command line.

Kernel panic - not syncing: Attempted to kill init!

Pid: 1, comm: init Not tainted 2.6.32-431.el6.x86_64 #1

Call Trace:

 [<ffffffff815271fa>] ? panic+0xa7/0x16f

 [<ffffffff81077622>] ? do_exit+0x862/0x870

 [<ffffffff8118a865>] ? fput+0x25/0x30

 [<ffffffff81077688>] ? do_group_exit+0x58/0xd0

 [<ffffffff81077717>] ? sys_exit_group+0x17/0x20

 [<ffffffff8100b072>] ? system_call_fastpath+0x16/0x1b

dracut Warning: No root device "block:/dev/disk/by-label/root_dev" found

%G

```

**Comment by djmitche** [comment]
Moving this over to https://bugzilla.mozilla.org/show_bug.cgi?id=1129958

**Pull request closed without merging**
